apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deploy
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:0.11.10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
            - name: entrypoint-script
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh # Mount a single file instead of the whole directory
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc
        - name: entrypoint-script
          hostPath:
            path: "/Users/heibalvin/Github/akashatek/Kiny/Deployment/LLM/entrypoint.sh"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-svc
  labels:
    app: ollama
spec:
  type: LoadBalancer
  ports:
    - port: 11434
      targetPort: 11434
  selector:
    app: ollama